export const IMAGES = {
  santorini: "https://images.unsplash.com/photo-1735446918160-af0b896b7a89?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxTYW50b3JpbmklMjBHcmVlY2UlMjBhZXJpYWwlMjBzdW5zZXR8ZW58MXx8fHwxNzc0MDUxMTQwfDA&ixlib=rb-4.1.0&q=80&w=1080",
  bali: "https://images.unsplash.com/photo-1576475706812-822620fc23ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxCYWxpJTIwcmljZSUyMHRlcnJhY2VzJTIwdHJvcGljYWx8ZW58MXx8fHwxNzc0MDUxMTQxfDA&ixlib=rb-4.1.0&q=80&w=1080",
  iceland: "https://images.unsplash.com/photo-1681834418277-b01c30279693?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJY2VsYW5kJTIwbm9ydGhlcm4lMjBsaWdodHMlMjBsYW5kc2NhcGV8ZW58MXx8fHwxNzc0MDUxMTQxfDA&ixlib=rb-4.1.0&q=80&w=1080",
  tokyo: "https://images.unsplash.com/photo-1613488328514-e424950c0b0d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxUb2t5byUyMHN0cmVldCUyMG5lb24lMjBuaWdodHxlbnwxfHx8fDE3NzQwNTExNDF8MA&ixlib=rb-4.1.0&q=80&w=1080",
  cappadocia: "https://images.unsplash.com/photo-1680204412403-73110934f5aa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxDYXBwYWRvY2lhJTIwaG90JTIwYWlyJTIwYmFsbG9vbnN8ZW58MXx8fHwxNzc0MDUxMTQyfDA&ixlib=rb-4.1.0&q=80&w=1080",
  maldives: "https://images.unsplash.com/photo-1662792721650-545a15f07ff6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxNYWxkaXZlcyUyMG92ZXJ3YXRlciUyMHZpbGxhJTIwb2NlYW58ZW58MXx8fHwxNzc0MDUxMTQyfDA&ixlib=rb-4.1.0&q=80&w=1080",
  alps: "https://images.unsplash.com/photo-1695135210748-d4f7d649bb42?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxTd2lzcyUyMEFscHMlMjBtb3VudGFpbiUyMGhpa2luZ3xlbnwxfHx8fDE3NzQwNTExNDJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  morocco: "https://images.unsplash.com/photo-1702057830533-2afff81a57f2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxNb3JvY2NvJTIwTWFycmFrZWNoJTIwY29sb3JmdWwlMjBtYXJrZXR8ZW58MXx8fHwxNzc0MDUxMTQzfDA&ixlib=rb-4.1.0&q=80&w=1080",
  dubai: "https://images.unsplash.com/photo-1773829126358-1e5f4e5aa532?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxEdWJhaSUyMHNreWxpbmUlMjBtb2Rlcm4lMjBhcmNoaXRlY3R1cmV8ZW58MXx8fHwxNzc0MDUxMTQzfDA&ixlib=rb-4.1.0&q=80&w=1080",
  patagonia: "https://images.unsplash.com/photo-1710444388055-5120c63dce41?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxQYXRhZ29uaWElMjBnbGFjaWVyJTIwbW91bnRhaW4lMjBsYWkxfGVufDF8fHx8MTc3NDA1MTE0NHww&ixlib=rb-4.1.0&q=80&w=1080",
  avatarFemale: "https://images.unsplash.com/photo-1668547424841-ecdec6b3b1e7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3b21hbiUyMHRyYXZlbGVyJTIwcG9ydHJhaXQlMjBhZHZlbnR1cmV8ZW58MXx8fHwxNzc0MDUxMTQ0fDA&ixlib=rb-4.1.0&q=80&w=1080",
  avatarMale: "https://images.unsplash.com/photo-1578173257188-2c095b0aef8b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYW4lMjBleHBsb3JlciUyMHBvcnRyYWl0JTIwb3V0ZG9vcnxlbnwxfHx8fDE3NzQwNTExNDV8MA&ixlib=rb-4.1.0&q=80&w=1080",
  // Krasnodar Krai
  sochi: "https://images.unsplash.com/photo-1722259038068-3ed12c947c6c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxTb2NoaSUyMEJsYWNrJTIwU2VhJTIwY29hc3QlMjByZXNvcnR8ZW58MXx8fHwxNzc0MDYyMTkwfDA&ixlib=rb-4.1.0&q=80&w=1080",
  krasnodar: "https://images.unsplash.com/photo-1740566496207-474637859f40?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxLcmFzbm9kYXIlMjBjaXR5JTIwcGFyayUyMGFlcmlhbHxlbnwxfHx8fDE3NzQwNjIxOTJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  caucasus: "https://images.unsplash.com/photo-1759490936290-933a1680bca3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxDYXVjYXN1cyUyMG1vdW50YWlucyUyMGhpa2luZyUyMGdyZWVufGVufDF8fHx8MTc3NDA2MjE5MXww&ixlib=rb-4.1.0&q=80&w=1080",
  vineyard: "https://images.unsplash.com/photo-1762362611583-8151f0a2c112?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx2aW5leWFyZCUyMHdpbmUlMjB0YXN0aW5nJTIwc3Vuc2V0fGVufDF8fHx8MTc3NDAzMDAzM3ww&ixlib=rb-4.1.0&q=80&w=1080",
  waterfall: "https://images.unsplash.com/photo-1664849275192-503e4c864380?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3YXRlcmZhbGwlMjBmb3Jlc3QlMjBjYW55b24lMjByaXZlcnxlbnwxfHx8fDE3NzQwNjIxOTJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  blackSeaCliff: "https://images.unsplash.com/photo-1772149808380-fc4f7c3e0d9a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxCbGFjayUyMFNlYSUyMGNvYXN0JTIwY2xpZmYlMjBzdW5zZXR8ZW58MXx8fHwxNzc0MDYyMTkyfDA&ixlib=rb-4.1.0&q=80&w=1080",
  dolphin: "https://images.unsplash.com/photo-1764331979883-9ffa4f951350?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkb2xwaGluJTIwb2NlYW4lMjB0dXJxdW9pc2UlMjB3YXRlcnxlbnwxfHx8fDE3NzQwNjIxOTN8MA&ixlib=rb-4.1.0&q=80&w=1080",
  mountainLake: "https://images.unsplash.com/photo-1753372623416-bc8bf85eab06?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb3VudGFpbiUyMGxha2UlMjBhbHBpbmUlMjByZWZsZWN0aW9ufGVufDF8fHx8MTc3NDA2MjE5M3ww&ixlib=rb-4.1.0&q=80&w=1080",
  teaPlantation: "https://images.unsplash.com/photo-1553337787-17961c0990db?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0ZWElMjBwbGFudGF0aW9uJTIwZ3JlZW4lMjBoaWxsc3xlbnwxfHx8fDE3NzM5OTU2NDF8MA&ixlib=rb-4.1.0&q=80&w=1080",
  dolmen: "https://images.unsplash.com/photo-1761769231977-73b1d278f151?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhbmNpZW50JTIwZG9sbWVuJTIwc3RvbmUlMjBtb251bWVudHxlbnwxfHx8fDE3NzQwNjIxOTR8MA&ixlib=rb-4.1.0&q=80&w=1080",
  kayak: "https://images.unsplash.com/photo-1762943107260-d080e13266b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxrYXlhayUyMHJpdmVyJTIwcmFwaWRzJTIwYWR2ZW50dXJlfGVufDF8fHx8MTc3NDA2MjE5NHww&ixlib=rb-4.1.0&q=80&w=1080",
  paragliding: "https://images.unsplash.com/photo-1759340875463-30962542e44d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYXJhZ2xpZGluZyUyMG1vdW50YWlucyUyMHNjZW5pY3xlbnwxfHx8fDE3NzQwNjIxOTV8MA&ixlib=rb-4.1.0&q=80&w=1080",
  avatarGuideF: "https://images.unsplash.com/photo-1549015239-87a56d550fb6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxydXNzaWFuJTIwd29tYW4lMjBndWlkZSUyMHBvcnRyYWl0JTIwb3V0ZG9vcnN8ZW58MXx8fHwxNzc0MDYyMTk1fDA&ixlib=rb-4.1.0&q=80&w=1080",
  avatarGuideM: "https://images.unsplash.com/photo-1768742893706-cc70c231ff10?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYW4lMjBtb3VudGFpbiUyMGd1aWRlJTIwYWR2ZW50dXJlJTIwcG9ydHJhaXR8ZW58MXx8fHwxNzc0MDYyMTk2fDA&ixlib=rb-4.1.0&q=80&w=1080",
  avatarBlogger: "https://images.unsplash.com/photo-1581537328138-e2d565883979?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3b21hbiUyMHRyYXZlbCUyMGJsb2dnZXIlMjBwb3J0cmFpdCUyMHNtaWxpbmd8ZW58MXx8fHwxNzc0MDYyMTk2fDA&ixlib=rb-4.1.0&q=80&w=1080",
};

export interface Post {
  id: string;
  image: string;
  author: string;
  authorAvatar: string;
  description: string;
  likes: number;
  comments: number;
  excursionId?: string;
  isQuiz?: boolean;
  quizQuestion?: string;
}

export interface Comment {
  id: string;
  postId: string;
  author: string;
  authorAvatar: string;
  text: string;
  timeAgo: string;
  likes: number;
}

export const mockComments: Comment[] = [
  { id: "c1", postId: "p1", author: "Марина К.", authorAvatar: "", text: "Невероятные фото! Хочу туда 😍", timeAgo: "5 мин", likes: 12 },
  { id: "c2", postId: "p1", author: "Дмитрий В.", authorAvatar: "", text: "Были там в прошлом году, это лучшее место!", timeAgo: "20 мин", likes: 8 },
  { id: "c3", postId: "p1", author: "Алиса П.", authorAvatar: "", text: "Подскажите, какой сезон лучший для поездки?", timeAgo: "1 ч", likes: 3 },
  { id: "c4", postId: "p2", author: "Олег М.", authorAvatar: "", text: "Потрясающий закат! 🌅", timeAgo: "10 мин", likes: 15 },
  { id: "c5", postId: "p2", author: "Елена С.", authorAvatar: "", text: "Какой камерой снимали?", timeAgo: "30 мин", likes: 2 },
  { id: "c6", postId: "p3", author: "Наталья Р.", authorAvatar: "", text: "Обожаю такие маршруты!", timeAgo: "15 мин", likes: 7 },
  { id: "c7", postId: "p3", author: "Сергей Л.", authorAvatar: "", text: "Сколько стоит экскурсия?", timeAgo: "45 мин", likes: 1 },
  { id: "c8", postId: "p4", author: "Ирина Б.", authorAvatar: "", text: "Мы тоже были, рекомендуем всем!", timeAgo: "2 ч", likes: 9 },
  { id: "c9", postId: "p5", author: "Павел Н.", authorAvatar: "", text: "Красота неописуемая 🏔", timeAgo: "3 мин", likes: 4 },
  { id: "c10", postId: "p5", author: "Анна Г.", authorAvatar: "", text: "Хочу забронировать, есть места на апрель?", timeAgo: "1 ч", likes: 6 },
  { id: "c11", postId: "p6", author: "Максим Д.", authorAvatar: "", text: "Лучший организатор!", timeAgo: "8 мин", likes: 11 },
  { id: "c12", postId: "p7", author: "Виктория З.", authorAvatar: "", text: "Спасибо за такой контент! ❤️", timeAgo: "25 мин", likes: 5 },
  { id: "c13", postId: "p8", author: "Андрей К.", authorAvatar: "", text: "А можно с детьми?", timeAgo: "40 мин", likes: 2 },
  { id: "c14", postId: "p9", author: "Юлия Т.", authorAvatar: "", text: "Уже забронировали на следующий месяц!", timeAgo: "2 ч", likes: 14 },
];

export interface Excursion {
  id: string;
  title: string;
  location: string;
  image: string;
  rating: number;
  reviewCount: number;
  price: string;
  duration: string;
  description: string;
  category: string;
  organizerId: string;
}

export interface Organizer {
  id: string;
  name: string;
  avatar: string;
  rating: number;
  description: string;
  followers: number;
  phone?: string;
  email?: string;
  website?: string;
}

export const organizers: Organizer[] = [
  {
    id: "org1",
    name: "Horizon Adventures",
    avatar: IMAGES.avatarMale,
    rating: 4.9,
    description: "Премиальные авторские туры по самым красивым местам мира. Более 500 экскурсий за 10 лет работы.",
    followers: 12400,
    phone: "+7 (900) 123-45-67",
    email: "info@horizon-adv.ru",
    website: "horizon-adventures.ru",
  },
  {
    id: "org2",
    name: "WanderLux Travel",
    avatar: IMAGES.avatarFemale,
    rating: 4.7,
    description: "Откройте мир с комфортом. Индивидуальный подход к каждому путешественнику.",
    followers: 8900,
    phone: "+7 (900) 234-56-78",
    email: "hello@wanderlux.ru",
    website: "wanderlux.ru",
  },
  {
    id: "org3",
    name: "Кубань-Тур",
    avatar: IMAGES.avatarGuideM,
    rating: 4.8,
    description: "Авторские экскурсии по Краснодарскому краю. Горы, море, вино и история — покажем всё!",
    followers: 15200,
    phone: "+7 (861) 345-67-89",
    email: "tour@kuban-tour.ru",
    website: "kuban-tour.ru",
  },
  {
    id: "org4",
    name: "Сочи Эксплорер",
    avatar: IMAGES.avatarGuideF,
    rating: 4.9,
    description: "Лучшие маршруты Большого Сочи. Каньоны, водопады, дольмены и секретные пляжи.",
    followers: 9800,
    phone: "+7 (862) 456-78-90",
    email: "explore@sochi-explorer.ru",
    website: "sochi-explorer.ru",
  },
  {
    id: "org5",
    name: "Анапа Live",
    avatar: IMAGES.avatarBlogger,
    rating: 4.6,
    description: "Семейный отдых и приключения на побережье Анапы и Геленджика. Дельфины, виноградники и закаты.",
    followers: 7300,
    phone: "+7 (861) 567-89-01",
    email: "live@anapa-live.ru",
    website: "anapa-live.ru",
  },
];

export const excursions: Excursion[] = [
  {
    id: "exc1",
    title: "Закаты Санторини",
    location: "Санторини, Греция",
    image: IMAGES.santorini,
    rating: 4.9,
    reviewCount: 324,
    price: "€120",
    duration: "4 часа",
    description: "Незабываемая прогулка по белоснежным улочкам Ии с профессиональным гидом. Вы увидите самый красивый закат в мире, посетите винодельню и попробуете местную кухню.",
    category: "Романтика",
    organizerId: "org1",
  },
  {
    id: "exc2",
    title: "Рисовые террасы Бали",
    location: "Убуд, Бали",
    image: IMAGES.bali,
    rating: 4.8,
    reviewCount: 256,
    price: "$85",
    duration: "6 часов",
    description: "Путешествие по знаменитым террасам Тегаллаланг. Медитация на рассвете, урок резьбы по дереву и традиционный балийский обед.",
    category: "Природа",
    organizerId: "org2",
  },
  {
    id: "exc3",
    title: "Северное сияние",
    location: "Рейкьявик, Исландия",
    image: IMAGES.iceland,
    rating: 4.7,
    reviewCount: 189,
    price: "€200",
    duration: "5 часов",
    description: "Ночная охота за Aurora Borealis. Горячие источники, исландский суп и фотосессия под звёздами.",
    category: "Приключения",
    organizerId: "org1",
  },
  {
    id: "exc4",
    title: "Неоновый Токио",
    location: "Токио, Япония",
    image: IMAGES.tokyo,
    rating: 4.6,
    reviewCount: 412,
    price: "¥15000",
    duration: "8 часов",
    description: "Погружение в мегаполис будущего. Акихабара, Сибуя, стритфуд-тур и караоке в аутентичном баре.",
    category: "Город",
    organizerId: "org2",
  },
  {
    id: "exc5",
    title: "Воздушные шары Каппадокии",
    location: "Каппадокия, Турция",
    image: IMAGES.cappadocia,
    rating: 5.0,
    reviewCount: 567,
    price: "€180",
    duration: "3 часа",
    description: "Полёт на воздушном шаре над сказочными ландшафтами на рассвете. Шампанское и завтрак с видом.",
    category: "Романтика",
    organizerId: "org1",
  },
  {
    id: "exc6",
    title: "Мальдивский рай",
    location: "Мальдивы",
    image: IMAGES.maldives,
    rating: 4.9,
    reviewCount: 198,
    price: "$350",
    duration: "Полный день",
    description: "Снорклинг с мантами, обед на песчаной косе и закат на яхте.",
    category: "Пляж",
    organizerId: "org2",
  },
  {
    id: "exc7",
    title: "Альпийский трекинг",
    location: "Церматт, Швейцария",
    image: IMAGES.alps,
    rating: 4.8,
    reviewCount: 145,
    price: "CHF 150",
    duration: "7 часов",
    description: "Маршрут с видом на Маттерхорн. Горные луга, альпийский сыр и панорамные площадки.",
    category: "Активный",
    organizerId: "org1",
  },
  {
    id: "exc8",
    title: "Краски Марракеша",
    location: "Марракеш, Марокко",
    image: IMAGES.morocco,
    rating: 4.5,
    reviewCount: 203,
    price: "€60",
    duration: "5 часов",
    description: "Лабиринты медины, дворец Бахия, площадь Джемаа-эль-Фна и мастер-класс по марокканской кухне.",
    category: "Культура",
    organizerId: "org2",
  },
  // Краснодарский край
  {
    id: "exc9",
    title: "Орлиные скалы и Агурские водопады",
    location: "Сочи, Краснодарский край",
    image: IMAGES.waterfall,
    rating: 4.9,
    reviewCount: 412,
    price: "₽3 500",
    duration: "5 часов",
    description: "Треккинг по живописному ущелью к каскаду Агурских водопадов. Подъём на Орлиные скалы с панорамой на Кавказский хребет и Чёрное море. Легенда о Прометее и пикник у горной реки.",
    category: "Природа",
    organizerId: "org4",
  },
  {
    id: "exc10",
    title: "Винный тур «Абрау-Дюрсо»",
    location: "Абрау-Дюрсо, Краснодарский край",
    image: IMAGES.vineyard,
    rating: 4.8,
    reviewCount: 287,
    price: "₽4 200",
    duration: "6 часов",
    description: "Посещение легендарного винодельческого завода. Дегустация 7 сортов шампанского, прогулка по озеру Абрау, гастроужин с видом на виноградники и световое шоу фонтанов.",
    category: "Гастро",
    organizerId: "org3",
  },
  {
    id: "exc11",
    title: "Каньон Псахо и Дзыхринское ущелье",
    location: "Адлер, Краснодарский край",
    image: IMAGES.blackSeaCliff,
    rating: 4.7,
    reviewCount: 198,
    price: "₽2 800",
    duration: "4 часа",
    description: "Мокрый и сухой каньоны Псахо — невероятные скальные образования, покрытые мхом и самшитом. Купание в природных чашах и фотосессия среди реликтового леса.",
    category: "Приключения",
    organizerId: "org4",
  },
  {
    id: "exc12",
    title: "Дельфины Чёрного моря",
    location: "Анапа, Краснодарский край",
    image: IMAGES.dolphin,
    rating: 4.6,
    reviewCount: 156,
    price: "₽5 500",
    duration: "3 часа",
    description: "Морская прогулка на яхте с наблюдением за афалинами в естественной среде. Снорклинг, купание в открытом море и дегустация свежих устриц на борту.",
    category: "Пляж",
    organizerId: "org5",
  },
  {
    id: "exc13",
    title: "Горное озеро Кардывач",
    location: "Красная Поляна, Краснодарский край",
    image: IMAGES.mountainLake,
    rating: 5.0,
    reviewCount: 89,
    price: "₽6 000",
    duration: "Полный день",
    description: "Поход к одному из самых красивых высокогорных озёр Кавказа на высоте 1838 м. Изумрудная вода, снежные вершины и альпийские луга. Только для подготовленных путешественников.",
    category: "Активный",
    organizerId: "org3",
  },
  {
    id: "exc14",
    title: "Чайные плантации Мацесты",
    location: "Сочи, Краснодарский край",
    image: IMAGES.teaPlantation,
    rating: 4.5,
    reviewCount: 234,
    price: "₽2 200",
    duration: "3 часа",
    description: "Самые северные чайные плантации в мире! Экскурсия по производству, дегустация 5 сортов краснодарского чая с видом на горы, мастер-класс по сбору чайного листа.",
    category: "Гастро",
    organizerId: "org4",
  },
  {
    id: "exc15",
    title: "Дольмены Пшады",
    location: "Геленджик, Краснодарский край",
    image: IMAGES.dolmen,
    rating: 4.4,
    reviewCount: 178,
    price: "₽3 000",
    duration: "5 часов",
    description: "Путешествие к загадочным мегалитам возрастом 5000 лет. Поход через реликтовый лес, переправа через горные реки и посещение группы из 9 дольменов.",
    category: "Культура",
    organizerId: "org3",
  },
  {
    id: "exc16",
    title: "Рафтинг на реке Мзымта",
    location: "Адлер, Краснодарский край",
    image: IMAGES.kayak,
    rating: 4.8,
    reviewCount: 342,
    price: "₽4 500",
    duration: "4 часа",
    description: "Адреналиновый сплав по главной реке Сочи! Пороги 2-3 категории сложности, профессиональные инструкторы, баня на берегу и шашлык после сплава.",
    category: "Активный",
    organizerId: "org4",
  },
  {
    id: "exc17",
    title: "Параглайдинг над Красной Поляной",
    location: "Красная Поляна, Краснодарский край",
    image: IMAGES.paragliding,
    rating: 4.9,
    reviewCount: 267,
    price: "₽7 000",
    duration: "2 часа",
    description: "Полёт на параплане с высоты 2200 м с видом на Кавказский хребет и Чёрное море. Видеосъёмка полёта в подарок, горячий глинтвейн после приземления.",
    category: "Приключения",
    organizerId: "org3",
  },
  {
    id: "exc18",
    title: "Набережная Геленджика на закате",
    location: "Геленджик, Краснодарский край",
    image: IMAGES.sochi,
    rating: 4.5,
    reviewCount: 145,
    price: "₽1 800",
    duration: "3 часа",
    description: "Прогулка по самой длинной набережной в России (14 км). Фотосессия у Белой невесты, дегустация местного мороженого и наблюдение за закатом с мыса Толстый.",
    category: "Романтика",
    organizerId: "org5",
  },
  {
    id: "exc19",
    title: "Трекинг к горе Фишт",
    location: "Лагонаки, Краснодарский край",
    image: IMAGES.caucasus,
    rating: 4.7,
    reviewCount: 98,
    price: "₽8 500",
    duration: "2 дня",
    description: "Двухдневный поход к легендарной горе Фишт (2867 м) через плато Лагонаки. Ночёвка в горном приюте, ледник, водопады и невероятные рассветы.",
    category: "Активный",
    organizerId: "org3",
  },
  {
    id: "exc20",
    title: "Гастротур по Краснодару",
    location: "Краснодар",
    image: IMAGES.krasnodar,
    rating: 4.6,
    reviewCount: 312,
    price: "₽3 200",
    duration: "5 часов",
    description: "Кулинарная прогулка по столице Кубани. Центральный рынок, крафтовые пивоварни, кубанский борщ и чурчхела. Посещение парка Галицкого и стрит-арт района.",
    category: "Гастро",
    organizerId: "org5",
  },
];

export const posts: Post[] = [
  {
    id: "p1",
    image: IMAGES.cappadocia,
    author: "Horizon Adventures",
    authorAvatar: IMAGES.avatarMale,
    description: "Рассвет в Каппадокии — это то, что нужно увидеть хотя бы раз в жизни 🎈",
    likes: 2847,
    comments: 156,
    excursionId: "exc5",
  },
  {
    id: "p2",
    image: IMAGES.waterfall,
    author: "Сочи Эксплорер",
    authorAvatar: IMAGES.avatarGuideF,
    description: "Агурские водопады после дождя — мощь и красота! Вода обрушивается с 30-метровой высоты 💧🏔️",
    likes: 3456,
    comments: 189,
    excursionId: "exc9",
  },
  {
    id: "p3",
    image: IMAGES.vineyard,
    author: "Кубань-Тур",
    authorAvatar: IMAGES.avatarGuideM,
    description: "Золотая осень в Абрау-Дюрсо. Виноградники, шампанское и закат над озером 🍷✨",
    likes: 4201,
    comments: 234,
    excursionId: "exc10",
  },
  {
    id: "p4",
    image: IMAGES.mountainLake,
    author: "Кубань-Тур",
    authorAvatar: IMAGES.avatarGuideM,
    description: "Озеро Кардывач — бирюзовое зеркало в объятиях Кавказских гор. Сюда нельзя доехать, только дойти 🥾",
    likes: 5678,
    comments: 312,
    excursionId: "exc13",
  },
  {
    id: "p5",
    image: IMAGES.paragliding,
    author: "Кубань-Тур",
    authorAvatar: IMAGES.avatarGuideM,
    description: "Когда весь Кавказ под ногами, а впереди — только море и небо. Параглайдинг над Красной Поляной 🪂",
    likes: 3890,
    comments: 201,
    excursionId: "exc17",
    isQuiz: true,
    quizQuestion: "Какой вид активного отдыха вам ближе?",
  },
  {
    id: "p6",
    image: IMAGES.teaPlantation,
    author: "Сочи Эксплорер",
    authorAvatar: IMAGES.avatarGuideF,
    description: "Знали ли вы, что в Сочи растёт самый северный чай в мире? Мацестинские плантации — зелёное чудо 🍵",
    likes: 2134,
    comments: 98,
    excursionId: "exc14",
  },
  {
    id: "p7",
    image: IMAGES.dolphin,
    author: "Анапа Live",
    authorAvatar: IMAGES.avatarBlogger,
    description: "Встреча с афалинами у берегов Анапы. Они подплывали прямо к яхте! Незабываемо 🐬",
    likes: 6012,
    comments: 345,
    excursionId: "exc12",
  },
  {
    id: "p8",
    image: IMAGES.kayak,
    author: "Сочи Эксплорер",
    authorAvatar: IMAGES.avatarGuideF,
    description: "Рафтинг на Мзымте — лучший способ почувствовать силу кавказских рек! Адреналин на максимуме 🌊",
    likes: 2967,
    comments: 167,
    excursionId: "exc16",
  },
  {
    id: "p9",
    image: IMAGES.blackSeaCliff,
    author: "Сочи Эксплорер",
    authorAvatar: IMAGES.avatarGuideF,
    description: "Каньон Псахо — место, где время остановилось. Мох, скалы и тишина реликтового леса 🌿",
    likes: 3345,
    comments: 178,
    excursionId: "exc11",
  },
  {
    id: "p10",
    image: IMAGES.caucasus,
    author: "Кубань-Тур",
    authorAvatar: IMAGES.avatarGuideM,
    description: "Плато Лагонаки — это другая планета. Альпийские луга, ледники и вершина Фишт на горизонте ⛰️",
    likes: 4567,
    comments: 256,
    excursionId: "exc19",
  },
  {
    id: "p11",
    image: IMAGES.krasnodar,
    author: "Анапа Live",
    authorAvatar: IMAGES.avatarBlogger,
    description: "Парк Галицкого в Краснодаре — шедевр ландшафтного дизайна. Гуляй и удивляйся на каждом шагу 🌳",
    likes: 2789,
    comments: 134,
    excursionId: "exc20",
  },
  {
    id: "p12",
    image: IMAGES.dolmen,
    author: "Кубань-Тур",
    authorAvatar: IMAGES.avatarGuideM,
    description: "Дольмены Пшады — загадка, которой 5000 лет. Кто и зачем их построил? Приезжайте разгадать 🗿",
    likes: 1890,
    comments: 112,
    excursionId: "exc15",
  },
  {
    id: "p13",
    image: IMAGES.sochi,
    author: "Анапа Live",
    authorAvatar: IMAGES.avatarBlogger,
    description: "Вечерний Геленджик — когда набережная зажигает огни, а бухта становится зеркалом 🌅",
    likes: 3210,
    comments: 156,
    excursionId: "exc18",
  },
  {
    id: "p14",
    image: IMAGES.santorini,
    author: "WanderLux Travel",
    authorAvatar: IMAGES.avatarFemale,
    description: "Белоснежные домики и бесконечная лазурь. Санторини никогда не надоедает ✨",
    likes: 3201,
    comments: 98,
    excursionId: "exc1",
  },
];

export const reviews = [
  { id: "r1", author: "Анна К.", rating: 5, text: "Невероятный опыт! Гид был просто потрясающий, всё организовано на высшем уровне.", date: "15 марта 2026" },
  { id: "r2", author: "Дмитрий М.", rating: 4, text: "Отличная экскурсия, красивые виды. Немного не хватило времени на фото.", date: "10 марта 2026" },
  { id: "r3", author: "Елена С.", rating: 5, text: "Это было лучшее путешествие в моей жизни! Обязательно вернусь.", date: "5 марта 2026" },
];

export const nearbyActivities = [
  { id: "a1", name: "Винодельня Sunset", type: "Дегустация", price: "€30", duration: "1.5 ч" },
  { id: "a2", name: "Пещерный ресторан", type: "Ужин", price: "€45", duration: "2 ч" },
  { id: "a3", name: "Фотосессия у маяка", type: "Фото", price: "€50", duration: "1 ч" },
  { id: "a4", name: "Тисо-самшитовая роща", type: "Прогулка", price: "₽500", duration: "2 ч" },
  { id: "a5", name: "Дегустация мёда на пасеке", type: "Гастро", price: "₽800", duration: "1 ч" },
  { id: "a6", name: "Баня на берегу реки", type: "Релакс", price: "₽2 000", duration: "2 ч" },
];